#!/bin/sh

echo "-----Normalizing Regular UFO..."
echo "-----Updating production names in Regular..."
#psfsetpsnames -p checkfix=fix -i source/glyph_data.csv source/Andika-Regular.ufo -x

echo "-----Updating glyph orders in Regular..."
#psfsetglyphorder -q --header sort_final_a -i source/glyph_data.csv source/Andika-Regular.ufo -p backup=False -x

echo "-----Normalizing other UFOs..."
psfnormalize -p checkfix=fix source/Kanchenjunga-Regular.ufo       &
psfnormalize -p checkfix=fix source/Kanchenjunga-Bold.ufo       &
wait

echo "-----Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -q source/Kanchenjunga.designspace 

# echo "-----Updating woff metadata file..."
# psfmakewoffmetadata -q -n "Andika" -i "org.sil.fonts" source/Andika-Regular.ufo

echo "-----Preflight completed!"
