#!/bin/sh

echo "-----Normalizing Regular UFO..."
echo "-----Updating production names in Regular..."
psfsetpsnames -q -p checkfix=none -i source/glyph_data.csv source/Kanchenjunga-Regular.ufo

echo "-----Updating glyph orders in Regular..."
psfsetglyphorder -q --header sort_final -i source/glyph_data.csv source/Kanchenjunga-Regular.ufo -p backup=False -x

echo "-----Normalizing other UFOs..."
psfnormalize -p checkfix=fix source/Kanchenjunga-Regular.ufo       &
psfnormalize -p checkfix=fix source/Kanchenjunga-Bold.ufo       &
wait

echo "-----Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -q source/Kanchenjunga.designspace 

echo "Updating woff metadata files..."
psfmakewoffmetadata -q -n  Kanchenjunga        -i org.sil.fonts source/*-Regular.ufo  -o "source/Kanchenjunga-WOFF-metadata.xml"

echo "Building internal fea..."
makefea -o source/Kanchenjunga-Regular.ufo/features.fea -l source/logs/Kanchenjunga-Regular-psfmakefea.log -i source/opentype/master.feax --omitaps "R, O, L" source/Kanchenjunga-Regular.ufo &
makefea -o source/Kanchenjunga-Bold.ufo/features.fea    -l source/logs/Kanchenjunga-Bold-psfmakefea.log    -i source/opentype/master.feax --omitaps "R, O, L" source/Kanchenjunga-Bold.ufo    &

wait

echo "-----Preflight completed!"
